module ProcessTracer
  class Trace
    @mode: Symbol
    @trace_depth: Integer
    @logging_pieces: Array[Hash[Symbol, untyped]]
    @start_time: Time

    @tracer: TracePoint

    def tracer: -> TracePoint
  end
end
